name: CI/CD NuGet

on:
  pull_request:
    types: [closed]
    branches: [main]
  push:
    branches: [main]

jobs:
  build-test-pack:
    runs-on: windows-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/AdventOfCode.Common/AdventOfCode.Common.slnx

      - name: Run tests with coverage
        run: dotnet test ./src/AdventOfCode.Common/Ved.AdventOfCode.Common.Tests/Ved.AdventOfCode.Common.Tests.csproj --collect:"XPlat Code Coverage"

#      - name: Check coverage
#        run: |
#          report=$(dotnet tool run coverlet ./src/AdventOfCode.Common/Ved.AdventOfCode.Common.Tests/bin/Debug/net10.0/Ved.AdventOfCode.Common.Tests.dll --target "dotnet" --targetargs "test --no-build")
#          coverage=$(echo $report | grep -oP 'Line coverage: \K[0-9]+')
#          if ($coverage -lt 80) {
#            Write-Host "Code coverage $coverage% is below threshold."
#            exit 1
#          }

      - name: Pack NuGet
        run: dotnet pack ./src/AdventOfCode.Common/Ved.AdventOfCode.Common/Ved.AdventOfCode.Common.csproj --configuration Release

      - name: Publish NuGet
        run: dotnet nuget push ./src/AdventOfCode.Common/Ved.AdventOfCode.Common/bin/Release/Ved.AdventOfCode.Common.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

